### ISSUE TITLE
rosbag2 split bags end to end testing

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#10]
## Description

Splitting rosbags was implemented over the other stories in this Epic - to finish up we want a complete end-to-end integration test that tests the whole feature.
Integration and E2E tests are written in the `rosbag2_tests` package of `ros2/rosbag2`.

* [x] ~~No max size provided~~ (This is interpreted as no splitting)
* [x] Max size provided but max size not reached
* [x] Max size provided and multiple files come out
* [ ] Playback works on all above cases
* [x] Metadata contains topic information for topics in all bags even if some bags don't have some topics
* [x] Bag size is at least the size specified in the bag splitting argument.

## Test Plan

E2E tests run and can be executed.

## Documentation Plan

Docstrings.

## Release Plan

Merge into the Master branch of `ros2/rosbag2`.

## Acceptance Criteria

* [x] The sqlite3 storage plugin is tested for the ability to write to multiple database files.
* [x] A unit test exists that creates multiple database files via the plugin's API.
* [x] E2E tests address all design requirements.
* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

N/A

**Comment by zmichaels11** [comment]
FYI: `test_rosbag_play_end_to_end` in `rosbag2 tests` is disabled. We should consider fixing this test

**Comment by zmichaels11** [comment]
WIP PR: https://github.com/ros2/rosbag2/pull/247

**Comment by zmichaels11** [comment]
Completed low-hanging-fruit for this PR.

**Comment by zmichaels11** [comment]
Found bug: https://github.com/ros2/rosbag2/issues/253

**Comment by zmichaels11** [comment]
- [ ] Open PR for bug fix: https://github.com/ros2/rosbag2/pull/254

**Comment by zmichaels11** [comment]
Found issue on `rosbag2_bag_v2` from changes we introduced: https://github.com/ros2/rosbag2_bag_v2/issues/17
- [ ] Open PR resolving issue: https://github.com/ros2/rosbag2_bag_v2/pull/16
