### ISSUE TITLE
[2d] Prepare ROSCon Security workshop slides

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#12]
## Description

Add workshop content to: https://docs.google.com/presentation/d/1xfCph3Wd5MaD96GPnMSvcDim_xXgqufusYs_AUzUzJ0/edit

Slides outline:

```
ROS 2 demo presentation
=> Alias Discovery Tool to know an app is running
=> Attack by publishing in /cmd_vel
=> Harden using SROS
=> Can’t attack by publishing on /cmd_vel anymore
=> But… ROS Sec Test, CPU / memory / disk attack
=> Containerize nodes to prevent the attack
=> Use roslaunch grouping feature to actually prevent the CPU attack from succeeding
=> ROS 2 Threat Model: here is a checklist of elements you should look at
=> Conclusion
```

## Spike Timeboxing

2 days

## Spike Outcome

* Slides: https://docs.google.com/presentation/d/1xfCph3Wd5MaD96GPnMSvcDim_xXgqufusYs_AUzUzJ0/edit

## Goals

* [ ] The slides are ready

**Comment by thomas-moulard** [comment]
Updated exit criteria - I'll update the slides, there is no "findings" for this spike.
