### ISSUE TITLE
As a rosbag2 developer, I want a compression interface so I can develop compression plugins

### ISSUE THREAD

**Issue by piraka9011** [ros-security/aws-roadmap#121]
## Description

A new compression interface class needs to be added to `rosbag2` so that new compression plugins can be developed for compressing messages and files.
The interface needs the following methods (at least):
* [x] Compress File
* [x] ~~Compress SerializedBagMessage~~
* [x] Get a compression ID

This interface should enable someone to use the PIMPL Idiom.

## Test Plan

Unit tests:
* File compression is called if file compression is in metadata.
* Message compression is called if message compression is in metadata.

## Documentation Plan

Docstrings

## Release Plan

* Merge in to master branch of rosbag2

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [Related PR](https://github.com/ros2/rosbag2/pull/218)

**Comment by zmichaels11** [comment]
@piraka9011 can you list any related PRs to this user story?

**Comment by piraka9011** [comment]
Related PR: https://github.com/ros2/rosbag2/pull/219

**Comment by zmichaels11** [comment]
Did you mean ros2/rosbag2#218 ?

**Comment by piraka9011** [comment]
Yes, thanks :)
