### ISSUE TITLE
Enable pages for `colcon` canary test failures

### ISSUE THREAD

**Issue by thomas-moulard** [ros-security/aws-roadmap#127]
## Description

As `colcon` does not directly have e2e testing, `colcon-bundle` [e2e test](https://github.com/colcon/colcon-bundle/blob/master/tox.ini) is assuming this role for our team. When a failure happens, our oncall should be paged, so that we notice problems quickly.

This ticket means basically updating the [.travis.yml](https://github.com/colcon/colcon-bundle/blob/master/.travis.yml) to:
*  send page the on-call if the build is failing.
* Add AWS robotics on-call paging alias as Travis secret
* Run nightly during work day so on-call is paged only in work hours

From Matt:
* e2e tests are not reliable, paging could be noisy
* Matt to add Canary information

## Test Plan

* Check that the page email is actually paging the oncall

## Documentation Plan

* Update the oncall runbook as needed.

## Release Plan

N/A - Will be enabled when merged to `master`.

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [Travis e-mail notification](https://docs.travis-ci.com/user/notifications#configuring-email-notifications)
* https://docs.pytest.org/en/latest/flaky.html

**Comment by zmichaels11** [comment]
TODO: open story to add GH Actions later

**Comment by piraka9011** [comment]
Closed in favor of #169
