### ISSUE TITLE
Add ros1 support to ros2 cross-compile tool

### ISSUE THREAD

**Issue by prajakta-gokhale** [ros-security/aws-roadmap#132]
## Description

Currently the [cross-compile](https://github.com/ros-tooling/cross_compile) tool cross compiles ROS 2 source files. We want the same tool to support cross compilation of ROS 1 source files.

Needs only Melodic and Kinetic ROS1 support.
This will only support REP 2000 Tier 1.
## Test Plan

* Manual testing by cross compiling ROS1 source packages for
  * ARMHF
  * ARM64
* New unit tests if necessary
* Automated end to end test for ROS 1 and ROS 2

## Documentation Plan

* README.md update to document new feature

## Release Plan

* Merge PR into `master`
* Bloom in Melodic and Kinetic

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

General usability changes going through clearing the way for ROS1 support
* [x] https://github.com/ros-tooling/cross_compile/pull/71
* [x] https://github.com/ros-tooling/cross_compile/pull/72
* [x] https://github.com/ros-tooling/cross_compile/pull/75
* [x] https://github.com/ros-tooling/cross_compile/pull/74
* [x] https://github.com/ros-tooling/cross_compile/pull/76
* [x] https://github.com/ros-tooling/cross_compile/pull/86
* [x] https://github.com/ros-tooling/cross_compile/pull/87
* [x] https://github.com/ros-tooling/cross_compile/pull/88 
* [x] https://github.com/ros-tooling/cross_compile/pull/89

## Resources

* [cross-compile repo](https://github.com/ros-tooling/cross_compile)
* [HelloWorld sample app](https://github.com/aws-robotics/aws-robomaker-sample-application-helloworld)

**Comment by emersonknapp** [comment]
General usability changes going through clearing the way for ROS1 support
* https://github.com/ros-tooling/cross_compile/pull/71
* https://github.com/ros-tooling/cross_compile/pull/72
* https://github.com/ros-tooling/cross_compile/pull/75
* https://github.com/ros-tooling/cross_compile/pull/74
* https://github.com/ros-tooling/cross_compile/pull/76

**Comment by prajakta-gokhale** [comment]
ROS1 support

* [ ] https://github.com/ros-tooling/cross_compile/pull/90

**Comment by prajakta-gokhale** [comment]
Currently developing GitHub Actions workflow to automate the e2e testing.

**Comment by prajakta-gokhale** [comment]
Bloom release:

* [ ] Dashing - https://github.com/ros/rosdistro/pull/23394
* [ ] Eloquent - https://github.com/ros/rosdistro/pull/23395

Since cross_compile is a ROS 2 package, we won't be bloom releasing it into Kinetic and Melodic right now. Instead, we want to convert cross_compile into a pure Python package and release it via `pip` so it is easier to maintain and release, and the installation steps remain same for all supported ROS distros (https://github.com/ros-tooling/cross_compile/issues/102).
