### ISSUE TITLE
ROS2 System Metrics Launch File

### ISSUE THREAD

**Issue by dabonnie** [ros-security/aws-roadmap#149]
## Description

Create a launch file to run the system metrics system cpu and system memory nodes.
 
## Test Plan

* Manual testing
* End to end integration test calling launch file

## Documentation Plan

* README.md update

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by prajakta-gokhale** [comment]
* [ ] Adding launch file: https://github.com/ros-tooling/system_metrics_collector/pull/63

**Comment by dabonnie** [comment]
Filed https://github.com/ros-security/aws-roadmap/issues/162 to capture configuration of the nodes in the launch file.
