### ISSUE TITLE
PeriodicCollectorNode can be dynamically started and stopped after running

### ISSUE THREAD

**Issue by dabonnie** [ros-security/aws-roadmap#156]
## Description

Allow each PeriodicCollectorNode to be dynamically started and stopped after running by using the [ROS2 lifecycle](https://design.ros2.org/articles/node_lifecycle.html).

## Test Plan

* Manual testing start and stop functionality bymanually invoking transitions from activate to deactivate
* Unit tests for start and stop functionality in the PeriodicCollectorNode class

## Documentation Plan

* README.md documentation update
* Document class

## Release Plan

* check in PR

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [Lifecycle Demo Code](https://github.com/ros2/demos/tree/master/lifecycle)

**Comment by zmichaels11** [comment]
Lifecycle manager?

**Comment by thomas-moulard** [comment]
See https://design.ros2.org/articles/node_lifecycle.html

**Comment by dabonnie** [comment]
> See https://design.ros2.org/articles/node_lifecycle.html

Thanks, already there! It's exactly what we need here :-)

**Comment by dabonnie** [comment]
Opened PR: https://github.com/ros-tooling/system_metrics_collector/pull/72

**Comment by dabonnie** [comment]
Opened PR for documentation: https://github.com/ros-tooling/system_metrics_collector/pull/77
