### ISSUE TITLE
Configure Launch File Nodes

### ISSUE THREAD

**Issue by dabonnie** [ros-security/aws-roadmap#162]
## Description

Once https://github.com/ros-security/aws-roadmap/issues/149 has been implemented, provide a configuration for the system cpu and system memory nodes via the launch file. Note: all nodes (system + process) should have a default topic of ```system_metrics``` (which should be added to the constructors). 

## Test Plan

* Manual testing with the launch file
* Unit test for input arguments in constructors, e.g., non empty topic names, valid periods

## Documentation Plan

* README.md update
  * section on how to launch the system nodes and their configuration parameters

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done

**Comment by mm318** [comment]
Relevant PR at https://github.com/ros-tooling/system_metrics_collector/pull/80.
