### ISSUE TITLE
Measure and average system virtual memory used

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#23]
## Description

Measure linux system vitrual memory used. Determine if a percentage should be reported instead of some byte scaling, as multiple platforms can have varying total memory sizes.

Use the sys/sysinfo.h to get free and total memory. Store the resulting measurement in a RunningStatistics averaging container.

## Test Plan

Unit tests with mock data. 

## Documentation Plan

Doc classes

## Release Plan

N/A

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by dabonnie** [comment]
Opened PR: https://github.com/ros-tooling/system_metrics_collector/pull/12
