### ISSUE TITLE
Measure and average system CPU %

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#27]
## Description

Measure linux system CPU % using /proc/stat (example found [here](https://github.com/aws-robotics/health-metrics-collector-ros1/blob/master/health_metric_collector/src/cpu_metric_collector.cpp)). Store the resulting measurement in a [RunningStatistics](https://code.amazon.com/packages/B9Ros2TopicStatistics/blobs/mainline/--/statistics/include/statistics/moving_average/running_statistics.hpp) averaging container. 

The `Collector` and `PeriodicMeasurement` nodes need to be implemented before the system CPU collector node can be implemented.

Note: the RunningStatistics class will need to be migrated to the utilties project defined in [ARF-3843](https://issues.amazon.com/issues/ARF-3843).

## Test Plan

* Unit tests for new classes and fake data can be used to simulate /proc/stat CPU information
* Provide main to run the node / class on a linux box

## Documentation Plan

Document code

## Release Plan

Merge PRs

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [Design Doc](https://quip-amazon.com/KzzfAUQeRkVY/WIP-Design-Doc-ROS2-Runtime-Metrics-System-Metrics)

**Comment by dabonnie** [comment]
Opened PR for the collector: https://github.com/ros-tooling/system_metrics_collector/pull/4

**Comment by dabonnie** [comment]
Opened PR for Periodic API: https://github.com/ros-tooling/system_metrics_collector/pull/6

**Comment by dabonnie** [comment]
Opened PR which adds measurement mechanism: https://github.com/ros-tooling/system_metrics_collector/pull/11
