### ISSUE TITLE
Define MetricsMessage

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#29]
## Description

Create the MetricsMessage and its components, following the format specified [here](https://quip-amazon.com/KzzfAUQeRkVY/WIP-Design-Doc-ROS2-Runtime-Metrics-System-Metrics#ccD9CA9r9GS), in a standalone package. 

The message definition should be generic enough to allow new arbitrary metrics to be published by user-defined applications, as well as supporting the System Metrics and Message Metrics use cases.

The package should live in a repository under ros-tooling.

## Test Plan

colcon build and test must pass
## Documentation Plan

Create README detailing message design and document fields

## Release Plan

To be released when a publishing node implements the code.

## Acceptance Criteria

* [x] Create a new repo in [ros-tooling](https://github.com/ros-tooling) org for System Metrics
* [ ] Add MessageMetrics message as separate package, get it reviewed and merged

Once all above items are checked, this story can be moved to done.

## Resources

* [Runtime (System) Metrics Design Doc](https://quip-amazon.com/KzzfAUQeRkVY/WIP-Design-Doc-ROS2-Runtime-Metrics-System-Metrics)

**Comment by dabonnie** [comment]
PR opened [here](https://github.com/ros-tooling/system_metrics_collector/pull/1).
