### ISSUE TITLE
[1d] Find out if Husarion platform provides battery state

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#54]
## Description

It is currently unclear if the Husarion platform publishes its battery state out of the box. This state is needed in order to aggregate information.

## Spike Timeboxing

1 Day

## Spike Outcome

If the required functionality is found to be missing, an issue will be filed to implement battery state publishing. Otherwise, the current functionality needs to be documented. 

## Goals

* [ ] Does Husarion code already publish /battery? If so, can we improve the documentation to make it discoverable? If not, can we implement this feature?

**Comment by piraka9011** [comment]
Per the new Husarion firmware [here](https://github.com/husarion/rosbot-firmware-new/tree/v0.9.1-dev#ros-communication):

> ROSbot publishes to: ... `/battery` with message type `sensor_msgs/BatteryState`
