### ISSUE TITLE
New cross-compilation tool needs ROS2 wiki documentation to clearly explain its use

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#59]
## Description

"As a ROS2 user, I want to read a ROS2 wiki to learn how to use cross_compile, so that I can compile my robot application for my target platform."

The tool is being created in https://github.com/ros-tooling/cross_compile/pull/20 - but the wiki documentation site will need updating 
https://github.com/ros2/ros2_documentation/blob/master/source/Tutorials/Cross-compilation.rst

## Test Plan

Jekyll build passes for update.

## Documentation Plan

This is a documentation task

## Release Plan

Merge PR to ros2_documentation

## Acceptance Criteria
 
* [ ] Documentation has been written, reviewed and merged.

Once all above items are checked, this story can be moved to done.

## Resources
* https://github.com/ros-tooling/cross_compile/pull/20
* https://github.com/ros2/ros2_documentation/blob/master/source/Tutorials/Cross-compilation.rst

**Comment by thomas-moulard** [comment]
Note: the doc should point to ros-tooling/cross_compile, meaning we need to push the code on the main repo.
