### ISSUE TITLE
Specify via CLI the max size of a rosbag2

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#6]
## Description

To enable a ROS2 user to split rosbag2 bag files, the ros2bag CLI needs to updated to expose the splitting features.

A new -b|--max-bag-size parameter needs to be added to the record command of the ros2 bag verb that specifies in bytes at what size the splitting should occur.

Python bindings in rosbag2_transport should also be updated to enable passing the size of the parameter to the rosbag2 library.

### Error checking
Specifically, we need to make sure that when the storage type is SQLite, then the user cannot specify a bag splitting size less than 84kb since that is the minimum size of the bagfile.

The following for example should not run and throw an error:

ros2 bag record -a -b 4096 -s sqlite
since the split size is 4kb (which is less than 84kb).

## Test Plan

* Manual testing
* Unit test 

## Documentation Plan

* docstrings
* update epilog of `ros2 bag record` command

## Release Plan

* merge into `ros2/rosbag2:master`

## Acceptance Criteria

* [x] ros2 bag record - takes new -b option and records split bag files
* [x] python bindings for rosbag2_transport have been updated - so that the commandline can use it
* [x] The CLI sanitizes input for split bag size

Once all above items are checked, this story can be moved to done.

## Resources

* [`rosbag2` repo](https://github.com/ros2/rosbag2)
* [Prajakta's previous PR](https://github.com/ros2/rosbag2/pull/158)
* [SO: Unit tests for argparse](https://stackoverflow.com/questions/49838007/python-unittest-with-argparse)
* [SO: How to unit test with argparse](https://stackoverflow.com/questions/18160078/how-do-you-write-tests-for-the-argparse-portion-of-a-python-module)

**Comment by prajakta-gokhale** [comment]
rosbag2 PRs:

* [ ] CLI option - https://github.com/ros2/rosbag2/pull/203
* [ ] CLI Sanitization - https://github.com/ros2/rosbag2/pull/226
