### ISSUE TITLE
Trial and measure performance of proposed approach (without internal code)

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#67]
## Description

We have proposed a high level approach to rosbag2 compression. Before we start on implementation, we want to manually try the approach, define a performance metric for it (size-based), and ~~compare that to ros1 bag sizes on some known inputs~~.

Basically - put split bags thru gzip or something and measure compression ratio. Then compare ~~size ros1 bag of the same data set~~ ros1 compression ratio to generated results.

## Test Plan

* Manual testing

## Documentation Plan

* Output an analysis of compression ratios on samples.

## Release Plan

* Output an analysis of compression ratios on samples and discuss with sim/app team.

## Acceptance Criteria

* [x] Get sample bags - Use bagfiles that already exist - don't run robomaker simulations ourself.
* [x] Approximate compression ratio performance of a 'split' rosbag2 file

Once all above items are checked, this story can be moved to done.

## Resources

"compression ratio ~4.5, could be as high as ~6.5 (images compressed the best)"

https://github.com/ros-security/aws-roadmap/blob/master/spike-findings/15-rosbag2-compression.md

**Comment by dabonnie** [comment]
Investigation results of compressing a written rosbag2 file.

Reference **13GB** file provided by the RoboMaker Team. Results are tabulated below:

|  Compression Algorithm |  Size (GB) | Ratio  | Time Taken  | 
|---|---|---|---|
| bzip2 (levels 1 & 9, no change)  | 1.8  | 7.2  | 8m42.868s  |  
| lz4 fast (default)  |  5.8 | 2.2  | 1m24.922s  |  
|  lz4 best (level 9) | 3.2  | 4.1  | 34m54.570s  |  
| lz4 mid (level 4)  |  4.4 | 3.0  | 3m32.974s  |  
| Zstandard (default=3)  |  2.6 |  5.0 |  1m50.756s |  
| Zstandard (level 7)  | 2.4  |  5.4 | 3m35.970s  |  
| Zstandard (level 1)  |  2.6 | 5.0  | 1m26.618s  |  
| Snappy  | 4.3   | 3.0  | 1m22.894s  |  

[Internal Amazon Doc Link](https://quip-amazon.com/39RdAmVZIRLo)

**Comment by dabonnie** [comment]
Next steps: trial and measure performance of compressing individual messages.
