### ISSUE TITLE
Compression commandline option

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#68]
## Description

I can specify via commandline to rosbag2 record, whether to use compression.

Option without a value is default compression method, but it can take a value and has a set of valid choices.

## Test Plan

* Manual testing
* Unit test for rosbag2 cli (take a look as sros2 for good examples)

## Documentation Plan

* README.md update
* cli -help update

## Release Plan

* check in PR

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by zmichaels11** [comment]
Duplicate of #124?

**Comment by piraka9011** [comment]
Closing in favor of #124
