### ISSUE TITLE
rosbag2 storage - SQLite database splitting

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#7]
## Description

`rosbag2` uses storage plugins (databases) that store the information collected from the topics.
These plugins are implemented in `rosbag2_storage_default_plugins`. The abstract interface for storage plugins are located in `rosbag2_storage`.

To enable `rosbag2` splitting, a new feature needs to be added to the SQLite plugin that can split a database. This requires SQLite to stop writing to a specific `.db3` file, create a new one, and start writing to another file .

## Test Plan

* Manual QA
* Unit tests

## Documentation Plan

* docstrings

## Release Plan

* merge to `ros2/rosbag2:master`

## Acceptance Criteria

* [x] The sqlite3 storage plugin has the ability to write to multiple database files
* [x] A unit test exists that creates multiple database files via the plugin's API
Once all above items are checked, this story can be moved to done.

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [ ] Release plan has been completed

**Comment by zmichaels11** [comment]
The work tracked by this user story was merged into ros2/rosbag2#184, which was merged into master.
