### ISSUE TITLE
As a ROS2 user, I want to make sure that I don't pass bad arguments to the ros2bag CLI so that I can safely play and record bag files

### ISSUE THREAD

**Issue by piraka9011** [ros-security/aws-roadmap#72]
## Description

The current ros2bag CLI does not have any input sanitization for splitting options. We need to make sure that whatever inputs the user passes that they are handled correctly.

Specifically, we need to make sure that when the storage type is SQLite, then the user cannot specify a bag splitting size less than 84kb since that is the minimum size of the bagfile.

The following for example should _not_ run and throw an error:
```
ros2 bag record -a -b 4096 -s sqlite
```
since the split size is 4kb (which is less than 84kb).

## Test Plan

* Manual testing
* Unit test for passing bad split size and good split sizes

## Documentation Plan

Update the Python argpaser help messages.

## Release Plan

* Merge to master branch of `ros2/rosbag2`

## Acceptance Criteria

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

**Comment by emersonknapp** [comment]
Wrapped this in as a requirement for https://github.com/ros-security/aws-roadmap/issues/6
