### ISSUE TITLE
rosbag2 Writer must choose to write to multiple files

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#8]
## Description

The current implementation of `rosbag2` assumes that there is only one bagfile URI to write to.
If we are to enable splitting features, we need to update the `rosbag2` `Writer` class to write to another bagfile.
This requires updating the `BagMetadata` structure to allow the representation of multiple bag files URIs and then adding the functionality to update the file URI that will be written to in the `rosbag2` `Writer` class.

## Test Plan

* Manual QA
* Unit tests

## Documentation Plan

* Docstrings

## Release Plan

PRs:
* [x] ros2/rosbag2#182
* [x] ros2/rosbag2#183
* [x] ros2/rosbag2#186
* [x] ros2/rosbag2#184 (API)
* [ ] ros2/rosbag2#185

## Acceptance Criteria

* [x] Update Writer class to support multiple files
* [x] Update bag metadata file to be a list of files instead of a single member
* [x] Bump the bag version
* [x] Make sure reader can't read this new bag version and error messages appropriately
* [x] Make sure old bags (bags written with only one file) can still be read

* [x] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed
Once all above items are checked, this story can be moved to done.

## Resources

* [Prajakta's previous PR](https://github.com/ros2/rosbag2/pull/158)

**Comment by zmichaels11** [comment]
PRs:
* [ ] ros2/rosbag2#182
* [ ] ros2/rosbag2#183
* [ ] ros2/rosbag2#186
* [ ] ros2/rosbag2#184
* [ ] ros2/rosbag2#185
