### ISSUE TITLE
ros2 bag play - new split bag file version

### ISSUE THREAD

**Issue by emersonknapp** [ros-security/aws-roadmap#9]
## Description

`rosbag2` only supports playing a single bag file at a time. As part of the changes made to for the `rosbag2` splitting feature, the bag recorder now updates a the bag's metadata with a list of bag files associated with a single recording session.

A description of the metadata can be found in `rosbag2_storage/bag_metadata`

The `rosbag2/sequential_reader` needs to be updated with the ability to read multiple bagfiles.
Bag file paths are specified as `rosbag2/storage_options` `uri`s.

Broadcasting the messages is already implemented in the `rosbag2_transport` library. The scope of this story is to only build the interface that opens and closes multiple files, not broadcast/play.

## Test Plan

Make sure locally that rosbag2 is able to read multiple bag files.
Write the unit tests that make sure:
* A list of file strings can be read in from the bag metadata 
* No regressions occur.

## Documentation Plan

C++ docstrings.

## Release Plan

Merge into the master branch of `ros2/rosbag2`.

## Acceptance Criteria

* [x] When I invoke ros2 bag play on our new version of split bags, it plays all of the recording in sequential order

* [ ] Code has been implemented, reviewed and merged.
* [ ] Test plan has been completed
* [ ] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* [`rosbag2` repo](https://github.com/ros2/rosbag2)
* [Prajakta's previous PR](https://github.com/ros2/rosbag2/pull/158)

**Comment by piraka9011** [comment]
Picking this up and working on fixing the tests for multifile reader.

**Comment by prajakta-gokhale** [comment]
Changes are in https://github.com/ros2/rosbag2/pull/206.
