### ISSUE TITLE
Add stubs for the new functions in the RMW implementations(fastrtps, opensplice, connext)

### ISSUE THREAD

**Issue by jaisontj** [ros-security/aws-roadmap#94]
## Description
Add stubs in the 3 RMW implementations for the functions added by [this](https://github.com/ros-security/aws-roadmap/issues/80)

## Test Plan
None 

## Documentation Plan
Comments for the respective functions

## Release Plan
Submit PR to the respective repositories.

## Acceptance Criteria
* [ ] Code has been implemented, reviewed and merged.

Once all above items are checked, this story can be moved to done.

**Comment by jaisontj** [comment]
[rmw_fastrtps PR](https://github.com/ros2/rmw_fastrtps/pull/333)

**Comment by mm318** [comment]
Additionally, the [rmw_cyclonedds PR](https://github.com/ros2/rmw_cyclonedds/pull/81).
