### ISSUE TITLE
As a ROSBag2 developer, I can create new Writer types so that I can extend the functionality of the ROSBag2 Writer.

### ISSUE THREAD

**Issue by piraka9011** [ros-security/aws-roadmap#98]
## Description

The current implementation of the `Writer` in ROSBag2 is a single class that writes messages to a storage plugin and metadata.
If we want to extend ROSBag2 with more features, we need to make an interface for a ROSBag2 developer to extend with the necessary features.

There will be a new `IWriter` class used as an interface. This will be used to _compose_ a `SequentialWriter`, which writes messages from a storage plugin in sequence and a `MultiFileWriter` which can write to storage plugins and split bag files.

## Test Plan

* Unit test for the `SequentialWriter` and the `MultiFileWriter`
* Integration tests are part of another user story.

## Documentation Plan

C++ Doxygen.

## Release Plan

Merge into the `master` branch of `ros2/rosbag2`.

## Acceptance Criteria

* [x] Code has been implemented, reviewed and merged.
* [x] Test plan has been completed
* [x] Release plan has been completed

Once all above items are checked, this story can be moved to done.

## Resources

* Most changes can be found in [aws-ros-dev/splitting-reader-changes](https://github.com/aws-ros-dev/rosbag2/tree/splitting/reader-changes)

**Comment by prajakta-gokhale** [comment]
This is done as part of https://github.com/ros2/rosbag2/pull/205.
